export const firstList = [
  { text: 'ASCENDING TRIANGLE', bg: '#2974B8' },
  { text: 'PENNANT - ВЫМПЕЛ', bg: '#4F8BC9' },
  { text: 'FLAG', bg: '#245FAB' },
  { text: 'CUP AND HANDLES', bg: '#0A4A94' },
  { text: 'DOUBLE BOTTOM', bg: '#395DA7' },
  { text: 'FALLING WEDGE', bg: '#203466' },
  { text: 'INVERSE HEAD AND SHOULDERS', bg: '#2974B8' },
  { text: 'ROUNDING BOTTOM', bg: '#4F8BC9' },
  { text: 'TRIPLE BOTTOM', bg: '#245FAB' },
  { text: 'DESCENDING TRIANGLE', bg: '#0A4A94' },
  { text: 'DOUBLE TOP', bg: '#395DA7' },
  { text: 'HEAD AND SHOULDERS', bg: '#203466' },
  { text: 'PRICE CHANNEL', bg: '#2974B8' },
  { text: 'TRIPLE TOP REVERSAL', bg: '#4F8BC9' },
  { text: 'SYMMETRICAL TRIANGLE', bg: '#245FAB' },
  { text: 'HAMMER', bg: '#0A4A94' },
  { text: 'INVERSE HAMMER', bg: '#395DA7' },
  { text: 'BULLISH ENGULFING', bg: '#203466' },
  { text: 'MORNING STAR', bg: '#2974B8' },
  { text: 'PIERCING LINE', bg: '#4F8BC9' },
  { text: 'THREE WHITE SOLDIERS', bg: '#245FAB' },
  { text: 'RISING THREE METHODS', bg: '#0A4A94' },
  { text: 'HANGING MAN', bg: '#395DA7' },
  { text: 'SHOOTING STAR', bg: '#203466' },
  { text: 'BEARISH ENGULFING', bg: '#2974B8' },
  { text: 'EVENING STAR', bg: '#4F8BC9' },
  { text: 'THREE BLACK CROWS', bg: '#245FAB' },
  { text: 'DARK CLOUD COVER', bg: '#0A4A94' },
  { text: 'DOJI', bg: '#395DA7' },
  { text: 'SPINNING TOP', bg: '#203466' },
  { text: 'FALLING THREE METHODS', bg: '#2974B8' },
  { text: 'HARAMI PATTERN', bg: '#4F8BC9' },
  { text: 'IMBALANCE', bg: '#245FAB' },
  { text: 'TWO CROWS', bg: '#0A4A94' },
  { text: 'THREE INSIDE UP', bg: '#395DA7' },
  { text: 'THREE INSIDE DOWN', bg: '#203466' },
  { text: 'THREE LINE STRIKE', bg: '#2974B8' },
  { text: 'THREE OUTSIDE UP', bg: '#4F8BC9' },
  { text: 'THREE OUTSIDE DDWN', bg: '#245FAB' },
  { text: 'THREE STARS IN THE SOUTH', bg: '#0A4A94' },
  { text: 'ABANDONED BABY', bg: '#395DA7' },
  { text: 'ADVANCE BLOCK', bg: '#203466' },
  { text: 'BELT-HOLD', bg: '#203466' },
]

export const secondList = [
  { text: 'BREAKWAY', bg: '#2974B8' },
  { text: 'CLOSING MARUBOZU', bg: '#4F8BC9' },
  { text: 'CONCEALING BABY SWALLOW', bg: '#245FAB' },
  { text: 'COUNTERATTACK', bg: '#0A4A94' },
  { text: 'DOJI STAR', bg: '#395DA7' },
  { text: 'DRAGONFLY DOJI', bg: '#203466' },
  { text: 'EVENING DOJI STAR', bg: '#2974B8' },
  { text: 'UP-GAP SIDE-BY-SIDE WHITE LINES', bg: '#4F8BC9' },
  {
    text: 'DOWN-GAP SIDE-BY-SIDE WHITE LINES',
    bg: '#245FAB',
  },
  { text: 'GRAVESTONE DOJI', bg: '#0A4A94' },
  { text: 'HARAMI CROSS PATTERN', bg: '#395DA7' },
  { text: 'HIGH-WAVE CANDLE', bg: '#203466' },
  { text: 'HIKKAKE PATTERN', bg: '#2974B8' },
  { text: 'MODIFIED HIKKAKE PATTERN', bg: '#4F8BC9' },
  { text: 'HOMING PIGEON', bg: '#245FAB' },
  { text: 'IDENTICAL THREE CROWS', bg: '#0A4A94' },
  { text: 'IN-NECK PATTERN', bg: '#395DA7' },
  { text: 'KICKING', bg: '#203466' },
  { text: 'BULL DETERMINED BY THE LONGER MARUBOZU', bg: '#2974B8' },
  { text: 'BEAR DETERMINED BY THE LONGER MARUBOZU', bg: '#4F8BC9' },
  { text: 'LADDER BOTTOM', bg: '#245FAB' },
  { text: 'LONG LEGGED DOJI', bg: '#0A4A94' },
  { text: 'MARUBOZU', bg: '#395DA7' },
  { text: 'MATCHING LOW', bg: '#203466' },
  { text: 'MAT HOLD', bg: '#2974B8' },
  { text: 'MORNING DOJI STAR', bg: '#4F8BC9' },
  { text: 'ON-NECK PATTERN', bg: '#245FAB' },
  { text: 'PIERCING PATTERN', bg: '#0A4A94' },
  { text: 'RICKSHAW MAN', bg: '#395DA7' },
  { text: 'SEPARATING LINES', bg: '#203466' },
  { text: 'SHORT LINE CANDLE', bg: '#2974B8' },
  { text: 'STALLED PATTERN', bg: '#4F8BC9' },
  { text: 'STICK SANDWICH', bg: '#245FAB' },
  {
    text: 'TAKURI (DRAGONFLY DOJI WITH VERY LONG LOWER SHADOW)',
    bg: '#0A4A94',
  },
  { text: 'THRUSTING PATTERN', bg: '#395DA7' },
  { text: 'TRISTAR PATTERN', bg: '#203466' },
  { text: 'UNIQUE 3 RIVER', bg: '#2974B8' },
  { text: 'UPSIDE GAP TWO CROWS', bg: '#4F8BC9' },
  { text: 'UPSIDE GAP THREE METHODS', bg: '#245FAB' },
  { text: 'DOWNSIDE GAP THREE METHODS', bg: '#0A4A94' },
]
