version: '3'

services:
  steven-signal-landing:
    image: ${REGISTRY}/${REPOSITORY}:${TAG}
    container_name: steven-signal-landing
    restart: always
    networks:
      - web-services

networks:
  web-services:
    external: true
